spring:
  profiles:
    active: postgres
  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
---
spring:
  profiles:
    active: postgres
  datasource:
    url: jdbc:postgresql://192.168.0.177:5432/batchexample
    username: hjjang
    password: hjjang123
    driver-class-name: org.postgresql.Driver
